
version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"
    environment:
      - AUTH=no
    links:
      - mongo
